### ISSUE TITLE
[WAS] Generate alternate GTFS packages for all dates

### ISSUE THREAD

**Issue by wklumpen** [transitcenter/ted-data#11]
Generate non-premium GTFS packages by removing the route IDs as identified in #10 

This requires the following steps:

1. Open the zipfile using the most recent version of GTFS-Lite
2. Using the routes identified, use [`delete_routes()`](https://gtfs-lite.readthedocs.io/en/latest/gtfs.html#gtfslite.gtfs.GTFS.delete_routes) on the package and save as a modified file with a `-LIMITED` tag
3. Upload the resulting limited GTFS files to the GDrive

**Comment by KaiHerrero** [comment]
Completed with https://github.com/transitcenter/ted-data/pull/23
