### ISSUE TITLE
Function to check if all analysis dates are valid for all feeds in all weeks

### ISSUE THREAD

**Issue by wklumpen** [transitcenter/ted-data#24]
We need a function to check that the GTFS feeds provided actually have service in the given date across all dates.

We should have a function called `check_valid_dates()` that goes through each GTFS file in a given date folder and checks the three dates we are running for that date. You can use the `gtfs-lite` function [`GTFS.valid_date()`](https://gtfs-lite.readthedocs.io/en/latest/gtfs.html#gtfslite.gtfs.GTFS.valid_date).

The function should print a list of feeds which do NOT cover the service date, for example:

```
Feed 2020-02-24/some-feed-slug-0.zip is not valid on 2020-02-26
```

The dates we are checking are the Wednesday and Saturday immediately following the folder date. There is also a run spreadsheet with the required data which can be attached.

**Comment by KaiHerrero** [comment]
closed with https://github.com/transitcenter/ted-data/pull/30
