### ISSUE TITLE
Access Scores Validation

### ISSUE THREAD

**Issue by wklumpen** [transitcenter/ted-data#31]
We need a workbook and/or set of scripts to produce some basic validation on the access scores.

I propose the following could be put together for a workbook, showing for all weeks as a time series

- [x] A plot of the maximum number of jobs accessible by a block group in a given week
- [x] A plot of the median value of access for each access destination type in a given week
- [x] A plot of the square root of the mean squared error from a previous dataset to the next for various access scores.

The MSRE would require taking a given block group ID and determining the difference from a given week to the next. For this you'll want an ordered sequence, which the Run Catalog should help with

**Comment by KaiHerrero** [comment]
branch 31-access-score-validation targets this issue

**Comment by KaiHerrero** [comment]
[https://github.com/transitcenter/ted-data/blob/31-access-score-validation/result_visualization.ipynb](url)
Created notebook for these, let me know what you think

**Comment by wklumpen** [comment]
Is this all in the workbook? If there's no need for a pull request we can just close it.

**Comment by KaiHerrero** [comment]
All in the notebook. I can close the branch!
